### ISSUE TITLE
plot demographic model

### ISSUE THREAD

**Issue by agladstein** [tskit-dev/tsviz#5]
As it sounds - create a figure of a demographic model. (e.g. like in momi https://momi2.readthedocs.io/en/latest/tutorial.html#Plotting-a-demography)
Maybe it's a more appropriate issue for msprime, since I'm not sure this actually would have anything to do with a tree sequence object.

**Comment by jeromekelleher** [comment]
I think this is an msprime issue @agladstein: see https://github.com/tskit-dev/msprime/issues/1

It's a non-trivial thing to do, I think.

This repo is for tree sequence visualisations, so I'm going to close the issue here.

**Comment by agladstein** [comment]
NP! Hard to keep track of everything!
